### ISSUE TITLE
Same bounding boxes published multiple times

### ISSUE THREAD

**Issue by cosama** [leggedrobotics/darknet_ros#150]
I have observed that relatively often the same `BoundingBoxes` message is published multiple times. 

I input images at roughly 15Hz and get bounding boxes out at about 20Hz, so it should be easy to check this behavior just with `rostopic hz /camera/rgb/image_raw` and `rostopic hz /darknet_ros/bounding_boxes`.

I don't really understand why but I think it has to do with threading in `YoloObjectDetector.cpp` in `void YoloObjectDetector::yolo()`. `void *YoloObjectDetector::publishInThread()` seems fine. 

The information in the bounding boxes are identical, except for the `Header`:

```
header: 
  seq: 57
  stamp: 
    secs: 1536697169
    nsecs: 397959597
  frame_id: "detection"
image_header: 
  seq: 116
  stamp: 
    secs: 1536697169
    nsecs: 131043656
  frame_id: "camera"
bounding_boxes: 
  - 
    Class: "person"
    probability: 0.763025939465
    xmin: 124
    ymin: 102
    xmax: 168
    ymax: 249
  - 
    Class: "person"
    probability: 0.517869532108
    xmin: 500
    ymin: 109
    xmax: 545
    ymax: 245
header: 
  seq: 58
  stamp: 
    secs: 1536697169
    nsecs: 438457349
  frame_id: "detection"
image_header: 
  seq: 116
  stamp: 
    secs: 1536697169
    nsecs: 131043656
  frame_id: "camera"
bounding_boxes: 
  - 
    Class: "person"
    probability: 0.763025939465
    xmin: 124
    ymin: 102
    xmax: 168
    ymax: 249
  - 
    Class: "person"
    probability: 0.517869532108
    xmin: 500
    ymin: 109
    xmax: 545
    ymax: 245
```
