### ISSUE TITLE
How to disable darknet console output?

### ISSUE THREAD

**Issue by zoombinis** [leggedrobotics/darknet_ros#284]
In config/ros.yaml I set:

```yaml
image_view:

  enable_opencv: false
  wait_key_delay: 1
  enable_console_output: false
```

But still darknet is producting console output that I do not want. Anyway to stop it?:

>person: 34%
person: 34%
person: 31%
person: 33%
person: 35%
person: 32%
person: 37%
person: 32%
person: 36%
person: 38%
person: 41%
person: 38%
