### ISSUE TITLE
/darknet_ros/bounding_boxes not publishing all bounding boxes!

### ISSUE THREAD

**Issue by SubZer0811** [leggedrobotics/darknet_ros#295]
I have trained yolov3 with my own dataset. It has 7 classes as follows:

- green_pole
- red_pole
- mid_pole
- gate
- obstacle
- red_bucket
- blue_bucket

Issue that I am facing is that, darknet works fine in detecting the objects in the given frame. But for some reason, it does not publish all the bounding boxes.

This is one output from running `roslaunch darknet_ros yolo_v3.launch`:
```
FPS:1.0
Objects:

gate: 100%
blue_bucket: 99%
red_bucket: 98%
red_bucket: 96%
green_pole: 94%
mid_pole: 88%
red_pole: 83%
red_bucket: 80%
```

and this is the output from running `rostopic echo /darknet_ros/bounding_boxes`:
```
header: 
  seq: 25
  stamp: 
    secs: 2212
    nsecs: 724000000
  frame_id: "detection"
image_header: 
  seq: 2649
  stamp: 
    secs: 2213
    nsecs: 790000000
  frame_id: "auv_v2/camera_link"
bounding_boxes: 
  - 
    probability: 0.87712687254
    xmin: 408
    ymin: 230
    xmax: 473
    ymax: 236
    id: 2
    Class: "mid_pole"
  - 
    probability: 0.996797680855
    xmin: 413
    ymin: 228
    xmax: 470
    ymax: 293
    id: 3
    Class: "gate"
  - 
    probability: 0.979921936989
    xmin: 270
    ymin: 256
    xmax: 284
    ymax: 270
    id: 5
    Class: "red_bucket"
  - 
    probability: 0.957235574722
    xmin: 232
    ymin: 257
    xmax: 246
    ymax: 269
    id: 5
    Class: "red_bucket"
  - 
    probability: 0.800785064697
    xmin: 312
    ymin: 256
    xmax: 325
    ymax: 270
    id: 5
    Class: "red_bucket"
  - 
    probability: 0.988205969334
    xmin: 193
    ymin: 257
    xmax: 208
    ymax: 269
    id: 6
    Class: "blue_bucket"
---
```

If anyone has the solution to this or needs to know anymore information, please let me know!
